export enum RequestNameResultCode {
    DBUS_REQUEST_NAME_REPLY_PRIMARY_OWNER = 1,
    DBUS_REQUEST_NAME_REPLY_IN_QUEUE = 2,
    DBUS_REQUEST_NAME_REPLY_EXISTS = 3,
    DBUS_REQUEST_NAME_REPLY_ALREADY_OWNER = 4
}